       IDENTIFICATION DIVISION.
       PROGRAM-ID. Program79.


       DATA DIVISION.
       WORKING-STORAGE SECTION.
      * Variables for Scope:METHOD_MAIN_CLASS_PROGRAM79_CHECKDIVISIBLE_GLOBAL
       01  ARGS_MAIN_-ARRAY.
           05  args_main    PIC X(100) OCCURS 100 TIMES.
      * Variables for Scope:BLOCK_METHOD_MAIN_CLASS_PROGRAM79_CHECKDIVISIBLE_GLOBAL
       01  n_main          PIC S9(5).
