import os
import subprocess
import shutil

JAVA_DIR = "./Java_files"
COBOL_DIR = "./COBOL_files"
ANTLR_DIR = os.path.abspath(os.path.join(os.getcwd(), "..", "Antlr"))

os.makedirs(COBOL_DIR, exist_ok=True)

separator = ";" if os.name == "nt" else ":"
classpath = f".{separator}antlr-4.13.2-complete.jar{separator}javaparser-core-3.25.8.jar"

# Path to the intermediate COBOL file generated by ParseTreeGeneration
intermediate_cobol_file = os.path.abspath(os.path.join("..", "finalCobolCode.cbl"))

# Clear the intermediate file before starting
with open(intermediate_cobol_file, "w", encoding="utf-8") as f:
    f.write("* COBOL code generated from Java files\n\n")

for file in os.listdir(JAVA_DIR):
    if file.endswith(".java"):
        classname = os.path.splitext(file)[0]
        java_file_path = os.path.abspath(os.path.join(JAVA_DIR, file))

        print(f"[INFO] Processing {file}")

        try:
            # Step 1: Run TestJavaVariableScoping
            subprocess.run(
                ["java", "-cp", classpath, "TestJavaVariableScoping", java_file_path],
                cwd=ANTLR_DIR,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )

            # Step 2: Run ParseTreeGeneration (writes to ../finalCobolCode.cbl)
            subprocess.run(
                ["java", "-cp", classpath, "ParseTreeGeneration", classname],
                cwd=ANTLR_DIR,
                check=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True
            )

            # Step 3: Read the intermediate COBOL file
            with open(intermediate_cobol_file, "r", encoding="utf-8") as f:
                cobol_code = f.read()

            # Step 4: Write COBOL code to COBOl_DIR/CLASSNAME.cob
            cobol_file_path = os.path.join(COBOL_DIR, classname + ".cob")
            with open(cobol_file_path, "w", encoding="utf-8") as f:
                f.write(cobol_code)

            print(f"[SUCCESS] Stored COBOL code for {classname} in {cobol_file_path}")

            # Optional: clear intermediate file before next iteration
            with open(intermediate_cobol_file, "w", encoding="utf-8") as f:
                f.write("")

        except subprocess.CalledProcessError as e:
            print(f"[ERROR] Failed for {file}")
            print(e.stderr)
